### PR TITLE
Add SP's ssh pub key

### PR DESCRIPTION
**Pull request by SionoiS**
O great infra master, i beg thee, allow me entrance into your sanctum.

### CODE REVIEW

**Review by jakubgs — CHANGES_REQUESTED** [review]
Please create a new password protected Ed25519 SSH key:
```
ssh-keygen -o -a 100 -t ed25519 -f ~/.ssh/id_ed25519 -C "joe@status.im"
```
Using your own `status.im` email as name.

**Comment by SionoiS** [comment]
Is it because I didn't use my status email for the key or because I can't use RSA2048?

**Review by jakubgs — APPROVED** [review]
Both. What do you need this access for?

**Comment by SionoiS** [comment]
At first I thought that I needed this for building and pushing nwaku v0.18.0 to docker then for the new feet but no.

I prefer not having access TBH.

**Pull request closed without merging**
